services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: tuyetanh0207
      POSTGRES_PASSWORD: postgrespw
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "32768:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
    driver: bridge
volumes:
  db: